const vragen = [

  { person: "Chocoladecake", answers: ["bloem", "suiker", "eieren", "boter", "chocolade"] },
  { person: "Appeltaart", answers: ["appel", "bloem", "boter", "suiker", "eieren"] },
  { person: "Pannenkoeken", answers: ["bloem", "melk", "eieren", "boter", "zout"] },
  { person: "Lasagne", answers: ["lasagnebladen", "gehakt", "tomatensaus", "kaas", "béchamelsaus"] },
  { person: "Spaghetti Bolognese", answers: ["spaghetti", "gehakt", "tomatensaus", "ui", "knoflook"] },
  { person: "Quiche Lorraine", answers: ["deeg", "eieren", "room", "bacon", "kaas"] },
  { person: "Brownies", answers: ["chocolade", "boter", "suiker", "eieren", "bloem"] },
  { person: "Tiramisu", answers: ["mascarpone", "eieren", "suiker", "lange vingers", "koffie"] },
  { person: "Groentesoep", answers: ["wortel", "prei", "selder", "aardappel", "bouillon"] },
  { person: "Pizza Margherita", answers: ["pizzadeeg", "tomatensaus", "mozzarella", "basilicum", "olijfolie"] },
  { person: "Kaastaart", answers: ["roomkaas", "eieren", "suiker", "boter", "koekjesbodem"] },
  { person: "Hamburger", answers: ["rundsvlees", "broodje", "sla", "tomaat", "ui"] },
  { person: "Ratatouille", answers: ["aubergine", "courgette", "paprika", "tomaat", "ui"] },
  { person: "Cannelés", answers: ["melk", "suiker", "bloem", "eieren", "vanille"] },
  { person: "Stoofvlees", answers: ["rundsvlees", "ui", "bier", "wortel", "kruidnagel"] },
  { person: "Kip tikka masala", answers: ["kip", "yoghurt", "tomatensaus", "kruiden", "room"] },
  { person: "Hartige muffins", answers: ["bloem", "eieren", "melk", "kaas", "ham"] },
  { person: "Focaccia", answers: ["bloem", "gist", "olijfolie", "water", "zout"] },
  { person: "Rijstpudding", answers: ["rijst", "melk", "suiker", "vanille", "room"] },
  { person: "Crème brûlée", answers: ["room", "eieren", "suiker", "vanille", "boter"] },
  { person: "Macarons", answers: ["amandelpoeder", "eiwit", "suiker", "poedersuiker", "kleurstof"] },
  { person: "Pompoensoep", answers: ["pompoen", "ui", "bouillon", "room", "kruiden"] },
  { person: "Hasselback aardappelen", answers: ["aardappel", "boter", "kruiden", "knoflook", "zout"] },
  { person: "Rode bieten salade", answers: ["rode biet", "geitenkaas", "walnoten", "rucola", "olie"] },
  { person: "Chili con carne", answers: ["gehakt", "tomaat", "bonen", "ui", "paprika"] },
  { person: "Mousse au chocolat", answers: ["chocolade", "eieren", "room", "suiker", "boter"] },
  { person: "Scones", answers: ["bloem", "boter", "suiker", "eieren", "melk"] },
  { person: "Gratin Dauphinois", answers: ["aardappel", "room", "boter", "knoflook", "kaas"] },
  { person: "Bananenbrood", answers: ["banaan", "bloem", "suiker", "boter", "eieren"] },
  { person: "Pavlova", answers: ["eiwit", "suiker", "maïzena", "room", "fruit"] },

  // 🌍 GESCHIEDENIS & WERELD
  { person: "Berlijnse Muur", answers: ["Oost-Duitsland", "West-Duitsland", "1989", "grens", "val"] },
  { person: "Napoleon Bonaparte", answers: ["Frankrijk", "keizer", "Waterloo", "Corsica", "Elba"] },
  { person: "Eerste Wereldoorlog", answers: ["1914", "1918", "loopgraven", "soldaten", "Vrede van Versailles"] },
  { person: "Romeinen", answers: ["keizer", "Colosseum", "Rome", "soldaten", "rijk"] },
  { person: "Franse Revolutie", answers: ["1789", "Bastille", "vrijheid", "gelijkheid", "broederschap"] },
  { person: "Koude Oorlog", answers: ["VS", "Sovjet-Unie", "atoombom", "spionage", "communisme"] },
  { person: "Titanic", answers: ["schip", "ijsberg", "1912", "zinken", "film"] },
  { person: "Middeleeuwen", answers: ["kastelen", "ridders", "kerk", "pest", "koningen"] },
  { person: "Tweede Wereldoorlog", answers: ["Hitler", "1945", "Duitsland", "geallieerden", "Holocaust"] },
  { person: "Industriële Revolutie", answers: ["fabrieken", "stoommachine", "Engeland", "arbeid", "technologie"] },
  { person: "Pater Damiaan", answers: ["leprapatiënten", "Molokai", "priester", "heilige", "België"] },
  { person: "Rijksmuseum", answers: ["Amsterdam", "Rembrandt", "Nachtwacht", "museum", "Nederland"] },
  { person: "Leopold II", answers: ["België", "Congo", "koning", "kolonie", "19e eeuw"] },
  { person: "Vincent van Gogh", answers: ["schilder", "Nederland", "zonnebloemen", "oor", "postimpressionisme"] },
  { person: "Henri Pirenne", answers: ["historicus", "België", "middeleeuwen", "Pirenne-these", "universiteit"] },
  { person: "Koninkrijk der Nederlanden", answers: ["monarchie", "grondwet", "1815", "Willem I", "geschiedenis"] },
  { person: "Sint-Romboutskathedraal", answers: ["Mechelen", "toren", "kerk", "gotisch", "België"] },
  { person: "Watersnoodramp 1953", answers: ["Nederland", "overstroming", "dijken", "Zeeland", "stormvloed"] },
  { person: "Rubens", answers: ["schilder", "barok", "Antwerpen", "17e eeuw", "doeken"] },
  { person: "Belforten in Vlaanderen", answers: ["UNESCO", "middeleeuwen", "klokkentoren", "steden", "erfgoed"] },

  // 🎬 FILM & TV
  { person: "Harry Potter", answers: ["tovenaar", "Zweinstein", "J.K. Rowling", "Hagrid", "Voldemort"] },
  { person: "Netflix", answers: ["streaming", "series", "abonnement", "Stranger Things", "film"] },
  { person: "De Mol", answers: ["televisieprogramma", "saboteur", "opdrachten", "kandidaten", "België"] },
  { person: "Friends", answers: ["Rachel", "Ross", "Monica", "New York", "sitcom"] },
  { person: "Marvel", answers: ["superhelden", "Iron Man", "Avengers", "Spider-Man", "films"] },
  { person: "Disney", answers: ["animatie", "Mickey Mouse", "films", "prinsessen", "themaparken"] },
  { person: "Game of Thrones", answers: ["draken", "Westeros", "Jon Snow", "Daenerys", "fantasy"] },
  { person: "James Bond", answers: ["spion", "007", "MI6", "film", "gadgets"] },
  { person: "Barbie", answers: ["pop", "film", "Margot Robbie", "Mattel", "roze"] },
  { person: "Studio 100", answers: ["Plop", "Samson", "K3", "Kabouter", "België"] },

  // 🎶 MUZIEK
  { person: "Beyoncé", answers: ["zangeres", "Destiny’s Child", "Jay-Z", "Single Ladies", "Amerika"] },
  { person: "Tomorrowland", answers: ["festival", "dance", "Boom", "DJ’s", "België"] },
  { person: "Elvis Presley", answers: ["rock", "King", "Graceland", "zanger", "1950s"] },
  { person: "The Beatles", answers: ["Lennon", "McCartney", "Liverpool", "band", "1960s"] },
  { person: "Stromae", answers: ["België", "Alors on danse", "zanger", "formidable", "rap"] },
  { person: "Taylor Swift", answers: ["zangeres", "pop", "Amerika", "album", "concert"] },
  { person: "Rapmuziek", answers: ["hiphop", "beats", "tekst", "freestyle", "flow"] },
  { person: "Queen", answers: ["Freddie Mercury", "Bohemian Rhapsody", "band", "rock", "Engeland"] },
  { person: "Ed Sheeran", answers: ["zanger", "gitaar", "Shape of You", "concert", "Engeland"] },
  { person: "ABBA", answers: ["Zweedse band", "Dancing Queen", "Eurovisie", "pop", "1970s"] },

  // 🧠 WETENSCHAP & TECHNOLOGIE
  { person: "Kunstmatige intelligentie", answers: ["robots", "ChatGPT", "algoritme", "technologie", "machine learning"] },
  { person: "Planeet Mars", answers: ["rood", "ruimte", "NASA", "rover", "planeet"] },
  { person: "Albert Einstein", answers: ["relativiteit", "fysica", "genie", "Duitsland", "E=mc²"] },
  { person: "Menselijk brein", answers: ["neuronen", "hersenen", "denken", "geheugen", "schedel"] },
  { person: "Elektriciteit", answers: ["stroom", "energie", "lamp", "batterij", "geleider"] },
  { person: "Internet", answers: ["www", "netwerk", "email", "computer", "communicatie"] },
  { person: "Weer", answers: ["regen", "wind", "zon", "temperatuur", "wolken"] },
  { person: "Maanlanding", answers: ["1969", "Neil Armstrong", "Apollo 11", "ruimte", "NASA"] },
  { person: "DNA", answers: ["erfelijkheid", "cel", "chromosomen", "gen", "dubbele helix"] },
  { person: "Water", answers: ["H2O", "drinken", "zee", "ijs", "regen"] },

  // ⚽ SPORT
  { person: "Rode Duivels", answers: ["België", "voetbal", "Courtois", "Lukaku", "EK"] },
  { person: "Olympische Spelen", answers: ["medailles", "sporters", "vlam", "goud", "vier jaar"] },
  { person: "Tennis", answers: ["bal", "racket", "Wimbledon", "Grand Slam", "serven"] },
  { person: "Formule 1", answers: ["auto", "race", "Max Verstappen", "snelheid", "Red Bull"] },
  { person: "Wielrennen", answers: ["fiets", "Tour de France", "Ronde van Vlaanderen", "peloton", "klimmen"] },
  { person: "Basketbal", answers: ["bal", "NBA", "dunk", "Michael Jordan", "LeBron James"] },
  { person: "Voetbal", answers: ["bal", "doelpunt", "FIFA", "scheidsrechter", "veld"] },
  { person: "Zwemmen", answers: ["water", "badmuts", "crawl", "Olympische Spelen", "Michael Phelps"] },
  { person: "Tour de France", answers: ["fiets", "gele trui", "bergetappe", "Frankrijk", "finish"] },
  { person: "Anderlecht", answers: ["club", "Brussel", "voetbal", "paars", "België"] },

  // 🇧🇪 BELGIË & NEDERLAND
  { person: "Brussel", answers: ["hoofdstad", "België", "Atomium", "taal", "EU"] },
  { person: "Antwerpen", answers: ["haven", "diamanten", "België", "mode", "kathedraal"] },
  { person: "Amsterdam", answers: ["grachten", "fiets", "Nederland", "Anne Frank", "museum"] },
  { person: "Koningsdag", answers: ["Nederland", "koning", "feest", "oranje", "april"] },
  { person: "Gent", answers: ["stad", "België", "Gravensteen", "universiteit", "feest"] },
  { person: "Vlaamse frieten", answers: ["aardappel", "frituur", "mayonaise", "België", "eten"] },
  { person: "Nederlandse koningshuis", answers: ["Willem-Alexander", "Máxima", "Oranje", "monarchie", "Den Haag"] },
  { person: "Ardennen", answers: ["natuur", "bos", "wandelen", "België", "bergen"] },
  { person: "Carnaval", answers: ["feest", "verkleden", "stoet", "muziek", "Brabant"] },
  { person: "Efteling", answers: ["pretpark", "Nederland", "sprookjes", "attractie", "Kaatsheuvel"] },


  // 🌍 GESCHIEDENIS (moeilijker)
  { person: "Marie Curie", answers: ["nobelprijs", "radioactiviteit", "scheikunde", "fysica", "Poolse"] },
  { person: "Charles Darwin", answers: ["evolutie", "natuurlijke selectie", "wetenschapper", "Engels", "On the Origin of Species"] },
  { person: "Val van Constantinopel", answers: ["1453", "Ottomaanse Rijk", "Byzantium", "Mehmet II", "Istanbul"] },
  { person: "Reformatie", answers: ["Luther", "kerk", "protestant", "95 stellingen", "16e eeuw"] },
  { person: "Koude Oorlog in Cuba", answers: ["rakettencrisis", "Kennedy", "Chroesjtsjov", "1962", "Sovjet-Unie"] },
  { person: "Nelson Mandela", answers: ["Zuid-Afrika", "apartheid", "gevangenis", "vrijheid", "president"] },
  { person: "Slag bij Waterloo", answers: ["1815", "Napoleon", "Wellington", "België", "nederlaag"] },
  { person: "Verlichting", answers: ["filosofie", "rede", "18e eeuw", "Voltaire", "Rousseau"] },
  { person: "Oude Egypte", answers: ["farao", "piramides", "Nijl", "Toetanchamon", "mummies"] },
  { person: "Russische Revolutie", answers: ["1917", "Lenin", "Tsaar", "Bolsjewieken", "communisme"] },

  // 🎬 FILM & TV (moeilijker)
  { person: "Stanley Kubrick", answers: ["regisseur", "The Shining", "2001: A Space Odyssey", "Eyes Wide Shut", "cinematografie"] },
  { person: "Francis Ford Coppola", answers: ["The Godfather", "Apocalypse Now", "regisseur", "Marlon Brando", "klassieker"] },
  { person: "La La Land", answers: ["musical", "Emma Stone", "Ryan Gosling", "Oscar", "Los Angeles"] },
  { person: "Parasite", answers: ["Zuid-Korea", "Bong Joon-ho", "Oscar", "klasseverschil", "thriller"] },
  { person: "Breaking Bad", answers: ["Walter White", "meth", "chemie", "Bryan Cranston", "serie"] },
  { person: "Twin Peaks", answers: ["David Lynch", "mysterie", "FBI", "Laura Palmer", "cultserie"] },
  { person: "Studio Ghibli", answers: ["Japan", "animatie", "Spirited Away", "My Neighbor Totoro", "Miyazaki"] },
  { person: "Citizen Kane", answers: ["filmklassieker", "Orson Welles", "Rosebud", "journalist", "1941"] },
  { person: "The Sopranos", answers: ["maffia", "Tony Soprano", "HBO", "New Jersey", "serie"] },
  { person: "The Truman Show", answers: ["Jim Carrey", "reality", "satire", "dome", "Peter Weir"] },

  // 🎶 MUZIEK (moeilijker)
  { person: "David Bowie", answers: ["Ziggy Stardust", "rock", "Engeland", "Space Oddity", "iconisch"] },
  { person: "Bob Dylan", answers: ["folk", "Nobelprijs", "Blowin’ in the Wind", "protestliederen", "Amerika"] },
  { person: "Pink Floyd", answers: ["The Wall", "rockband", "Brits", "psychedelisch", "Dark Side of the Moon"] },
  { person: "Nina Simone", answers: ["zangeres", "jazz", "burgerrechten", "Feeling Good", "pianiste"] },
  { person: "Kraftwerk", answers: ["Duitsland", "elektronische muziek", "synthesizer", "band", "invloedrijk"] },
  { person: "Freddie Mercury", answers: ["Queen", "zanger", "Bohemian Rhapsody", "live aid", "LGBTQ"] },
  { person: "Amy Winehouse", answers: ["Back to Black", "zangeres", "soul", "Londen", "overleden"] },
  { person: "Radiohead", answers: ["Brits", "rock", "Creep", "OK Computer", "alternatief"] },
  { person: "Miles Davis", answers: ["jazz", "trompettist", "Kind of Blue", "Amerika", "improvisatie"] },
  { person: "Billie Eilish", answers: ["zangeres", "pop", "Amerika", "Finneas", "Grammy’s"] },

  { person: "Wout van Aert", answers: ["belg", "wielrenner", "veldrijder", "visma-lease a bike", "belgisch kampioen"] },
  { person: "Koen Wauters", answers: ["zanger", "clouseau", "kris wauters", "presentator", "autocoureur"] },
  { person: "Lionel Messi", answers: ["voetballer", "argentijn", "inter miami", "barcelona", "wereldkampioen"] },
  { person: "Angela Merkel", answers: ["duits", "bondskanselier", "politicus", "cdu", "wetenschapper"] },
  { person: "Roger Federer", answers: ["tennisser", "zwitser", "wimbledon", "grand slam", "roland garros"] },
  { person: "Nafi Thiam", answers: ["atlete", "zevenkamp", "belg", "olympisch kampioen", "wereldkampioen"] },
  { person: "Rihanna", answers: ["zangeres", "barbados", "umbrella", "fenty", "super bowl"] },
  { person: "Elon Musk", answers: ["ondernemer", "tesla", "spacex", "twitter", "zuid-afrika"] },
  { person: "Cristiano Ronaldo", answers: ["voetballer", "portugees", "al-nassr", "real madrid", "juventus"] },
  { person: "Taylor Swift", answers: ["zangeres", "amerikaans", "eras tour", "blank space", "grammy"] },
  { person: "Barack Obama", answers: ["president", "verenigde staten", "democraat", "michelle obama", "nobelprijs"] },
  { person: "Adele", answers: ["zangeres", "brits", "hello", "grammy", "rolling in the deep"] },
  { person: "Rafael Nadal", answers: ["tennisser", "spaans", "roland garros", "grand slam", "real madrid fan"] },
  { person: "Serena Williams", answers: ["tennisster", "amerikaans", "grand slam", "olympisch goud", "venus williams"] },
  { person: "Lewis Hamilton", answers: ["formule 1", "mercedes", "wereldkampioen", "brits", "racen"] },
  { person: "Greta Thunberg", answers: ["klimaatactivist", "zweeds", "fridays for future", "milieu", "student"] },
  { person: "David Beckham", answers: ["voetballer", "engels", "manchester united", "real madrid", "model"] },
  { person: "Billie Eilish", answers: ["zangeres", "amerikaans", "bad guy", "finneas", "grammy"] },
  { person: "Mark Zuckerberg", answers: ["facebook", "meta", "ondernemer", "amerikaans", "miljardair"] },
  { person: "Usain Bolt", answers: ["sprinter", "jamaicaans", "wereldrecord", "olympisch kampioen", "atleet"] },
  { person: "Tom Cruise", answers: ["acteur", "mission impossible", "amerikaans", "top gun", "scientology"] },
  { person: "Emma Watson", answers: ["actrice", "harry potter", "brits", "hermione", "feministe"] },
  { person: "Kylian Mbappé", answers: ["voetballer", "frans", "paris saint-germain", "wereldkampioen", "real madrid"] },
  { person: "Kim Kardashian", answers: ["influencer", "amerikaans", "realityster", "skims", "kanye west"] },
  { person: "Zlatan Ibrahimović", answers: ["voetballer", "zweeds", "ac milan", "psg", "ajax"] },
  { person: "Dua Lipa", answers: ["zangeres", "albanees", "brits", "levitating", "popster"] },
  { person: "Lady Gaga", answers: ["zangeres", "amerikaans", "born this way", "actrice", "oscars"] },
  { person: "Ed Sheeran", answers: ["zanger", "brits", "shape of you", "gitaar", "divide"] },
  { person: "Johnny Depp", answers: ["acteur", "pirates of the caribbean", "amerikaans", "amber heard", "muzikant"] },
  { person: "Beyoncé", answers: ["zangeres", "amerikaans", "destiny’s child", "jay-z", "renaissance"] },
  { person: "Novak Djokovic", answers: ["tennisser", "servisch", "grand slam", "nummer één", "australian open"] },
  { person: "Jennifer Lopez", answers: ["zangeres", "amerikaans", "acteur", "on the floor", "ben affleck"] },
  { person: "Morgan Freeman", answers: ["acteur", "amerikaans", "stem", "shawshank redemption", "oscar"] },
  { person: "Leonardo DiCaprio", answers: ["acteur", "titanic", "oscar", "amerikaans", "milieuactivist"] },
  { person: "Shakira", answers: ["zangeres", "colombiaans", "waka waka", "barcelona", "gerard piqué"] },
  { person: "Bill Gates", answers: ["microsoft", "filantroop", "ondernemer", "amerikaans", "windows"] },
  { person: "Oprah Winfrey", answers: ["presentatrice", "amerikaans", "talkshow", "actrice", "miljardair"] },
  { person: "Harry Styles", answers: ["zanger", "one direction", "brits", "watermelon sugar", "acteur"] },
  { person: "Cristina Aguilera", answers: ["zangeres", "amerikaans", "genie in a bottle", "the voice", "grammy"] },
  { person: "Selena Gomez", answers: ["zangeres", "amerikaans", "actrice", "rare beauty", "disney"] },
  { person: "Miley Cyrus", answers: ["zangeres", "amerikaans", "wrecking ball", "hannah montana", "grammy"] },
  { person: "Keanu Reeves", answers: ["acteur", "matrix", "john wick", "canadees", "humble"] },
  { person: "Ariana Grande", answers: ["zangeres", "amerikaans", "thank u next", "grammy", "actrice"] },
  { person: "Céline Dion", answers: ["zangeres", "canadees", "my heart will go on", "titanic", "grammy"] },
  { person: "Vincent Kompany", answers: ["voetballer", "belg", "anderlecht", "manchester city", "trainer"] },
  { person: "Kevin De Bruyne", answers: ["voetballer", "belg", "manchester city", "middenvelder", "rood haar"] },
  { person: "Bart De Wever", answers: ["politicus", "n-va", "antwerpen", "burgemeester", "partijvoorzitter"] },
  { person: "Marthe De Pillecyn", answers: ["zangeres", "k3", "belgisch", "studio 100", "dansen"] },
  { person: "Julia Roberts", answers: ["actrice", "amerikaans", "pretty woman", "oscar", "smile"] },
  { person: "Brad Pitt", answers: ["acteur", "amerikaans", "fight club", "oscar", "angelina jolie"] },
  { person: "Angelina Jolie", answers: ["actrice", "amerikaans", "tomb raider", "humanitair", "brad pitt"] },
  { person: "Tom Hanks", answers: ["acteur", "forrest gump", "amerikaans", "cast away", "oscar"] },
  { person: "George Clooney", answers: ["acteur", "amerikaans", "ocean's eleven", "nespresso", "activist"] },
  { person: "Matt Damon", answers: ["acteur", "bourne", "amerikaans", "good will hunting", "oscar"] },
  { person: "Scarlett Johansson", answers: ["actrice", "amerikaans", "black widow", "avengers", "oscar"] },
  { person: "Chris Hemsworth", answers: ["acteur", "australisch", "thor", "avengers", "fit"] },
  { person: "Robert Downey Jr.", answers: ["acteur", "iron man", "avengers", "amerikaans", "oscar"] },
  { person: "Natalie Portman", answers: ["actrice", "amerikaans", "black swan", "star wars", "israelisch"] },
  { person: "Hugh Jackman", answers: ["acteur", "australisch", "wolverine", "musical", "les misérables"] },
  { person: "Johnny Logan", answers: ["zanger", "ier", "eurovisie", "what's another year", "hold me now"] },
  { person: "Jacques Brel", answers: ["zanger", "belg", "ne me quitte pas", "la chanson", "brussel"] },
  { person: "Eddy Merckx", answers: ["wielrenner", "belg", "tour de france", "de kannibaal", "recordhouder"] },
  { person: "Remco Evenepoel", answers: ["wielrenner", "belg", "wereldkampioen", "quick-step", "vuelta"] },
  { person: "Justine Henin", answers: ["tennisster", "belg", "roland garros", "nummer één", "olympisch kampioen"] },
  { person: "Kim Clijsters", answers: ["tennisster", "belg", "nummer één", "us open", "sportvrouw"] },
  { person: "Stromae", answers: ["zanger", "belg", "alors on danse", "formidable", "paul van haver"] },
  { person: "Angèle", answers: ["zangeres", "belg", "balance ton quoi", "bruxelles je t'aime", "pop"] },
  { person: "Dimitri Vegas", answers: ["dj", "belg", "like mike", "tomorrowland", "edm"] },
  { person: "Like Mike", answers: ["dj", "belg", "dimitri vegas", "broer", "tomorrowland"] },
  { person: "Felice Mazzu", answers: ["trainer", "belg", "charleroi", "anderlecht", "union"] },
  { person: "Peter Van de Veire", answers: ["presentator", "radio", "belg", "mnis", "vrt"] },
  { person: "Tom Waes", answers: ["acteur", "presentator", "reizen waes", "belg", "ondernemer"] },
  { person: "Bart Peeters", answers: ["zanger", "presentator", "belg", "radio", "tv"] },
  { person: "Philippe Geubels", answers: ["comedian", "belg", "tv", "lach", "flauwe humor"] },
  { person: "Alex Agnew", answers: ["comedian", "belg", "heavy metal", "podcast", "optredens"] },
  { person: "Michael Jordan", answers: ["basketbal", "amerikaans", "chicago bulls", "nba", "air jordan"] },
  { person: "LeBron James", answers: ["basketbal", "amerikaans", "los angeles lakers", "nba", "cleveland cavaliers"] },
  { person: "Kobe Bryant", answers: ["basketbal", "amerikaans", "lakers", "black mamba", "olympisch kampioen"] },
  { person: "Shaquille O'Neal", answers: ["basketbal", "amerikaans", "lakers", "analist", "nba"] },
  { person: "Michael Schumacher", answers: ["formule 1", "duits", "ferrari", "wereldkampioen", "racen"] },
  { person: "Max Verstappen", answers: ["formule 1", "nederlands", "red bull", "wereldkampioen", "snelheid"] },
  { person: "Charles Leclerc", answers: ["formule 1", "monaco", "ferrari", "coureur", "jong"] },
  { person: "Fernando Alonso", answers: ["formule 1", "spaans", "wereldkampioen", "aston martin", "ervaren"] },
  { person: "Sebastian Vettel", answers: ["formule 1", "duits", "ferrari", "red bull", "wereldkampioen"] },
  { person: "Lando Norris", answers: ["formule 1", "brits", "mclaren", "jong", "coureur"] },
  { person: "Cillian Murphy", answers: ["acteur", "ier", "peaky blinders", "oppenheimer", "oscar"] },
  { person: "Florence Pugh", answers: ["actrice", "brits", "midsommar", "little women", "oppenheimer"] },
  { person: "Timothée Chalamet", answers: ["acteur", "amerikaans", "dune", "wonka", "call me by your name"] },
  { person: "Zendaya", answers: ["actrice", "amerikaans", "euphoria", "spiderman", "dune"] },
  { person: "Pedro Pascal", answers: ["acteur", "chileens", "the mandalorian", "last of us", "amerikaans"] },
  { person: "Kate Winslet", answers: ["actrice", "brits", "titanic", "oscar", "the reader"] },
  { person: "Harrison Ford", answers: ["acteur", "indiana jones", "star wars", "amerikaans", "piloot"] },
  { person: "Tom Holland", answers: ["acteur", "spiderman", "brits", "marvel", "dans"] },
  { person: "Paul McCartney", answers: ["beatles", "muzikant", "brits", "zanger", "componist"] },
  { person: "John Lennon", answers: ["beatles", "zanger", "brits", "imagine", "muzikant"] },
  { person: "Ringo Starr", answers: ["beatles", "drummer", "brits", "muzikant", "zanger"] },
  { person: "George Harrison", answers: ["beatles", "gitarist", "brits", "muzikant", "spiritualiteit"] },
  { person: "Freddie Mercury", answers: ["queen", "zanger", "brits", "bohemian rhapsody", "overleden"] },
  { person: "Brian May", answers: ["queen", "gitarist", "astrofysicus", "brits", "krullen"] },
  { person: "David Bowie", answers: ["zanger", "brits", "starman", "acteur", "glam rock"] },
  { person: "Elvis Presley", answers: ["zanger", "amerikaans", "king of rock", "graceland", "overleden"] },
  { person: "Michael Jackson", answers: ["zanger", "amerikaans", "king of pop", "thriller", "moonwalk"] },
  { person: "Prince", answers: ["zanger", "amerikaans", "purple rain", "muzikant", "gitarist"] },
  { person: "Madonna", answers: ["zangeres", "amerikaans", "queen of pop", "like a virgin", "vogue"] },
  { person: "Whitney Houston", answers: ["zangeres", "amerikaans", "i will always love you", "the bodyguard", "grammy"] },
  { person: "Bruce Springsteen", answers: ["zanger", "amerikaans", "born in the usa", "the boss", "gitaar"] },
  { person: "Bob Dylan", answers: ["zanger", "amerikaans", "nobelprijs", "blowin in the wind", "gitaar"] },
  { person: "Elton John", answers: ["zanger", "brits", "pianist", "rocketman", "sir"] },
  { person: "Phil Collins", answers: ["zanger", "drummer", "genesis", "in the air tonight", "brits"] },
  { person: "Coldplay", answers: ["band", "brits", "chris martin", "yellow", "viva la vida"] },
  { person: "Alicia Keys", answers: ["zangeres", "amerikaans", "pianist", "fallin", "grammy"] },
  { person: "Eminem", answers: ["rapper", "amerikaans", "lose yourself", "slim shady", "detroit"] },
  { person: "Drake", answers: ["rapper", "canadees", "one dance", "hotline bling", "ovo"] },
  { person: "Kanye West", answers: ["rapper", "amerikaans", "yeezy", "producer", "kim kardashian"] },
  { person: "Jay-Z", answers: ["rapper", "amerikaans", "beyoncé", "empire state of mind", "ondernemer"] },
  { person: "Post Malone", answers: ["rapper", "amerikaans", "rockstar", "tattoos", "bierbrouwsel"] },
  { person: "The Weeknd", answers: ["zanger", "canadees", "blinding lights", "starboy", "abel tesfaye"] },
  { person: "Wout van Aert", answers: ["belg", "wielrenner", "veldrijder", "visma-lease a bike", "belgisch kampioen"] },
  { person: "Koen Wauters", answers: ["zanger", "clouseau", "kris wauters", "presentator", "autocoureur"] },
  { person: "Lionel Messi", answers: ["voetballer", "argentijn", "inter miami", "barcelona", "wereldkampioen"] },
  { person: "Cristiano Ronaldo", answers: ["voetballer", "portugees", "al-nassr", "real madrid", "juventus"] },
  { person: "Kylian Mbappé", answers: ["voetballer", "frans", "paris saint-germain", "wereldkampioen", "real madrid"] },
  { person: "Kevin De Bruyne", answers: ["voetballer", "belg", "manchester city", "middenvelder", "rood haar"] },
  { person: "Nafi Thiam", answers: ["atlete", "zevenkamp", "belg", "olympisch kampioen", "wereldkampioen"] },
  { person: "Rafael Nadal", answers: ["tennisser", "spaans", "roland garros", "grand slam", "real madrid fan"] },
  { person: "Novak Djokovic", answers: ["tennisser", "servisch", "grand slam", "nummer één", "australian open"] },
  { person: "Roger Federer", answers: ["tennisser", "zwitser", "wimbledon", "grand slam", "roland garros"] },
  { person: "Max Verstappen", answers: ["formule 1", "nederlands", "red bull", "wereldkampioen", "snelheid"] },
  { person: "Lewis Hamilton", answers: ["formule 1", "mercedes", "wereldkampioen", "brits", "racen"] },
  { person: "Michael Schumacher", answers: ["formule 1", "duits", "ferrari", "wereldkampioen", "racen"] },
  { person: "Eddy Merckx", answers: ["wielrenner", "belg", "tour de france", "de kannibaal", "recordhouder"] },
  { person: "Remco Evenepoel", answers: ["wielrenner", "belg", "wereldkampioen", "quick-step", "vuelta"] },
  { person: "Tom Waes", answers: ["acteur", "presentator", "reizen waes", "belg", "ondernemer"] },
  { person: "Philippe Geubels", answers: ["comedian", "belg", "tv", "lach", "flauwe humor"] },
  { person: "Elon Musk", answers: ["ondernemer", "tesla", "spacex", "x", "zuid-afrika"] },
  { person: "Bill Gates", answers: ["microsoft", "ondernemer", "filantroop", "windows", "amerikaans"] },
  { person: "Mark Zuckerberg", answers: ["facebook", "meta", "ondernemer", "amerikaans", "miljardair"] },
  { person: "Angela Merkel", answers: ["duits", "bondskanselier", "politicus", "cdu", "wetenschapper"] },
  { person: "Barack Obama", answers: ["president", "verenigde staten", "democraat", "michelle obama", "nobelprijs"] },
  { person: "Donald Trump", answers: ["president", "amerikaans", "zakenman", "republikein", "mar-a-lago"] },
  { person: "Greta Thunberg", answers: ["klimaatactivist", "zweeds", "fridays for future", "milieu", "student"] },
  { person: "Rihanna", answers: ["zangeres", "barbados", "umbrella", "fenty", "super bowl"] },
  { person: "Adele", answers: ["zangeres", "brits", "hello", "grammy", "rolling in the deep"] },
  { person: "Taylor Swift", answers: ["zangeres", "amerikaans", "eras tour", "blank space", "grammy"] },
  { person: "Beyoncé", answers: ["zangeres", "amerikaans", "destiny’s child", "jay-z", "renaissance"] },
  { person: "Ed Sheeran", answers: ["zanger", "brits", "shape of you", "gitaar", "divide"] },
  { person: "Lady Gaga", answers: ["zangeres", "amerikaans", "born this way", "actrice", "oscars"] },
  { person: "Dua Lipa", answers: ["zangeres", "albanees", "brits", "levitating", "popster"] },
  { person: "Stromae", answers: ["zanger", "belg", "alors on danse", "formidable", "paul van haver"] },
  { person: "Angèle", answers: ["zangeres", "belg", "balance ton quoi", "bruxelles je t'aime", "pop"] },
  { person: "Johnny Depp", answers: ["acteur", "pirates of the caribbean", "amerikaans", "amber heard", "muzikant"] },
  { person: "Leonardo DiCaprio", answers: ["acteur", "titanic", "oscar", "amerikaans", "milieuactivist"] },
  { person: "Brad Pitt", answers: ["acteur", "amerikaans", "fight club", "oscar", "angelina jolie"] },
  { person: "Angelina Jolie", answers: ["actrice", "amerikaans", "tomb raider", "humanitair", "brad pitt"] },
  { person: "Scarlett Johansson", answers: ["actrice", "amerikaans", "black widow", "avengers", "oscar"] },
  { person: "Tom Cruise", answers: ["acteur", "mission impossible", "amerikaans", "top gun", "scientology"] },
  { person: "Keanu Reeves", answers: ["acteur", "matrix", "john wick", "canadees", "humble"] },
  { person: "Zendaya", answers: ["actrice", "amerikaans", "euphoria", "spiderman", "dune"] },
  { person: "Cillian Murphy", answers: ["acteur", "ier", "peaky blinders", "oppenheimer", "oscar"] },
  { person: "Pedro Pascal", answers: ["acteur", "chileens", "the mandalorian", "last of us", "amerikaans"] },
  { person: "Vincent Kompany", answers: ["voetballer", "belg", "anderlecht", "manchester city", "trainer"] },
  { person: "Justine Henin", answers: ["tennisster", "belg", "roland garros", "nummer één", "olympisch kampioen"] },
  { person: "Kim Clijsters", answers: ["tennisster", "belg", "nummer één", "us open", "sportvrouw"] },

  // --- Top 5 LUXE MERKEN ---
  { person: "Top 5 luxe merken", answers: ["louis vuitton", "gucci", "chanel", "hermès", "prada"] },
  { person: "Top 5 automerken Duitsland", answers: ["mercedes", "bmw", "audi", "porsche", "volkswagen"] },
  { person: "Top 5 automerken Italië", answers: ["ferrari", "lamborghini", "maserati", "fiat", "alfa romeo"] },
  { person: "Top 5 automerken Japan", answers: ["toyota", "honda", "nissan", "mazda", "subaru"] },
  { person: "Top 5 automerken Frankrijk", answers: ["peugeot", "renault", "citroën", "bugatti", "ds"] },
  { person: "Top 5 automerken Verenigde Staten", answers: ["ford", "chevrolet", "tesla", "jeep", "cadillac"] },

  // --- Top 5 landen bevolking ---
  { person: "Top 5 landen met meeste bevolking", answers: ["china", "india", "verenigde staten", "indonesië", "pakistan"] },
  { person: "Top 5 landen met minste bevolking", answers: ["vatican", "tuvalu", "nauru", "palau", "san marino"] },
  { person: "Top 5 grootste landen qua oppervlakte", answers: ["rusland", "canada", "china", "verenigde staten", "brazilië"] },
  { person: "Top 5 kleinste landen qua oppervlakte", answers: ["vatican", "monaco", "nauru", "tuvalu", "san marino"] },

  // --- Top 5 voetballers Ballon d’Or winnaars ---
  { person: "Top 5 voetballers met meeste Ballon d’Ors", answers: ["lionel messi", "cristiano ronaldo", "michel platini", "johan cruyff", "marco van basten"] },
  { person: "Top 5 Belgische voetballers ooit", answers: ["eden hazard", "kevin de bruyne", "vincent kompany", "jan ceulemans", "thibaut courtois"] },
  { person: "Top 5 Europese voetbalclubs", answers: ["real madrid", "barcelona", "bayern münchen", "manchester united", "liverpool"] },
  { person: "Top 5 populairste sporten wereldwijd", answers: ["voetbal", "basketbal", "cricket", "tennis", "atletiek"] },
  { person: "Top 5 rijkste landen ter wereld", answers: ["qatar", "luxemburg", "singapore", "brunei", "ierland"] },
  { person: "Top 5 armste landen ter wereld", answers: ["burundi", "zuid-soedan", "malawi", "mozambique", "niger"] },
  { person: "Top 5 meest gesproken talen", answers: ["engels", "chinees", "spaans", "hindi", "arabisch"] },
  { person: "Top 5 langste rivieren ter wereld", answers: ["nijl", "amazone", "yangtze", "mississippi", "jenisej"] },
  { person: "Top 5 hoogste bergen ter wereld", answers: ["everest", "k2", "kangchenjunga", "lhotse", "makalu"] },
  { person: "Top 5 drukste luchthavens ter wereld", answers: ["atlanta", "dubai", "dallas", "heathrow", "tokyo haneda"] },
  { person: "Top 5 toeristische landen", answers: ["frankrijk", "spanje", "verenigde staten", "italië", "turkije"] },
  { person: "Top 5 grootste steden ter wereld", answers: ["tokyo", "delhi", "shanghai", "sao paulo", "mexico-stad"] },
  { person: "Top 5 kleinste hoofdsteden ter wereld", answers: ["vaticanstad", "funafuti", "nuku'alofa", "palikir", "tarawa"] },
  { person: "Top 5 duurste schilderijen ooit verkocht", answers: ["salvator mundi", "interchange", "the card players", "nafea faa ipoipo", "number 17a"] },
  { person: "Top 5 rijkste mensen ter wereld", answers: ["elon musk", "bernard arnault", "jeff bezos", "bill gates", "mark zuckerberg"] },
  { person: "Top 5 populairste festivals wereldwijd", answers: ["tomorrowland", "coachella", "glastonbury", "ultra music festival", "lollapalooza"] },
  { person: "Top 5 populairste Netflix-series", answers: ["stranger things", "the crown", "squid game", "the witcher", "bridgerton"] },
  { person: "Top 5 bekendste schilderijen ter wereld", answers: ["mona lisa", "sterrennacht", "de nachtwacht", "guernica", "het laatste avondmaal"] },
  { person: "Top 5 grootste eilanden ter wereld", answers: ["groenland", "nieuw-guinea", "borneo", "madagaskar", "sumatra"] },
  { person: "Top 5 beroemdste architecten", answers: ["frank lloyd wright", "le corbusier", "zaha hadid", "norman foster", "renzo piano"] },
  { person: "Top 5 meest bezochte musea", answers: ["louvre", "metropolitan museum", "british museum", "vatican museums", "prado"] },
  { person: "Top 5 grootste dieren ter wereld", answers: ["blauwe vinvis", "olifant", "giraffe", "neushoorn", "ijsbeer"] },
  { person: "Top 5 meest bekeken YouTube-kanalen", answers: ["tseries", "cocomelon", "set india", "pewdiepie", "kids dino"] },
  { person: "Top 5 duurste auto’s ter wereld", answers: ["bugatti la voiture noire", "rolls-royce sweptail", "pagani zonda hp barchetta", "koenigsegg ccxr trevita", "lamborghini veneno"] },
  { person: "Top 5 snelste dieren ter wereld", answers: ["cheetah", "vliegende gier", "pijlstaartrog", "zwaluw", "antilope"] },
  { person: "Top 5 populairste koffiesoorten", answers: ["arabica", "robusta", "liberica", "excelsa", "kona"] },
  { person: "Top 5 grootste oceanen", answers: ["pazifische oceaan", "atlantic oceaan", "indische oceaan", "zuidelijke oceaan", "arctische oceaan"] },
  { person: "Top 5 meest gedronken frisdranken", answers: ["coca-cola", "pepsi", "fanta", "sprite", "mountain dew"] },
  { person: "Top 5 meest populaire social media platforms", answers: ["facebook", "instagram", "tiktok", "twitter", "snapchat"] },
  { person: "Top 5 grootste techbedrijven ter wereld", answers: ["apple", "microsoft", "amazon", "google", "meta"] },
  { person: "Top 5 bekendste stripfiguren", answers: ["superman", "batman", "spiderman", "homer simpson", "mickey mouse"] },
  { person: "Top 5 grootste steden van Afrika", answers: ["lagos", "cairo", "kinshasa", "johannesburg", "nairobi"] },
  { person: "Top 5 beroemdste films van de 21e eeuw", answers: ["avatar", "inception", "the dark knight", "avengers endgame", "titanic"] },
  { person: "Top 5 populairste muziekinstrumenten", answers: ["gitaar", "piano", "drums", "viool", "saxofoon"] },
  { person: "Top 5 meest succesvolle videogames", answers: ["minecraft", "grand theft auto v", "tetris", "fortnite", "wii sports"] },
  { person: "Top 5 grootste rivieren van Europa", answers: ["volga", "rijn", "danube", "dnieper", "donau"] },
  { person: "Top 5 bekendste videogamepersonages", answers: ["mario", "link", "sonic", "pikachu", "lara croft"] },
  { person: "Top 5 populairste fastfoodketens", answers: ["mcdonalds", "burger king", "kfc", "subway", "pizza hut"] },
  { person: "Top 5 populairste smartphones", answers: ["iphone", "samsung galaxy", "xiaomi", "oppo", "oneplus"] },
  { person: "Top 5 grootste bioscoopketens wereldwijd", answers: ["amc", "regal", "cineworld", "cinemark", "kinepolis"] },
  { person: "Top 5 meest bekeken sportevenementen", answers: ["fifa wereldbeker", "olympische spelen", "super bowl", "tour de france", "wimbledon"] },
  { person: "Top 5 grootste luchtvaartmaatschappijen", answers: ["american airlines", "delta", "lufthansa", "emirates", "united"] },
  { person: "Top 5 bekendste wetenschappers", answers: ["einstein", "newton", "curie", "darwin", "galilei"] },
  { person: "Top 5 meest bezochte pretparken", answers: ["magic kingdom", "disneyland california", "disneyland paris", "universal studios florida", "tokyo disneyland"] },
  { person: "Top 5 populairste hondenrassen", answers: ["labrador retriever", "german shepherd", "golden retriever", "bulldog", "beagle"] },
  { person: "Top 5 populairste kattenrassen", answers: ["siamees", "britse korthaar", "maine coon", "pers", "ragdoll"] },
  { person: "Top 5 bekende festivals in België", answers: ["tomorrowland", "rock werchter", "gentse feesten", "pukkelpop", "dranouter"] },
  { person: "Top 5 beroemdste detectives", answers: ["sherlock holmes", "hercule poirot", "miss marple", "sam spade", "philip marlowe"] },
  { person: "Top 5 meest verkochte boeken", answers: ["bijbel", "don quichot", "harry potter", "lord of the rings", "alchemist"] },
  { person: "Top 5 beroemdste voetbalstadions", answers: ["santiago bernabeu", "camp nou", "old trafford", "allianz arena", "maracana"] },
  { person: "Top 5 populairste yogastijlen", answers: ["hatha", "vinyasa", "ashtanga", "yin", "kundalini"] },
  { person: "Top 5 bekendste boardgames", answers: ["monopoly", "chess", "risk", "cluedo", "settlers of catan"] },
  { person: "Top 5 populairste sneakermerken", answers: ["nike", "adidas", "puma", "reebok", "converse"] },
  { person: "Top 5 bekendste tekenfilms", answers: ["simpsons", "spongebob", "looney tunes", "adventure time", "tom & jerry"] },
  { person: "Top 5 duurste steden om te wonen", answers: ["hong kong", "zurich", "singapore", "tokyo", "parijs"] },
  { person: "Top 5 landen met meeste UNESCO werelderfgoederen", answers: ["italië", "china", "spanje", "duitsland", "frankrijk"] },
  { person: "Top 5 meest gebruikte programmeertalen", answers: ["python", "javascript", "java", "c#", "c++"] },
  { person: "Top 5 grootste zeehavens", answers: ["shanghai", "singapore", "shenzhen", "ningbo", "hong kong"] },
  { person: "Top 5 bekendste modellen", answers: ["gisele bündchen", "kendall jenner", "bella hadid", "naomi campbell", "cara delevingne"] },
  { person: "Top 5 meest bekeken films op Netflix", answers: ["bird box", "red notice", "stranger things", "the gray man", "squid game"] },
  { person: "Top 5 populairste sporten in België", answers: ["voetbal", "wielrennen", "tennis", "basketbal", "hockey"] },
  { person: "Top 5 bekendste rockbands", answers: ["queen", "the beatles", "rolling stones", "led zeppelin", "pink floyd"] },
  { person: "Top 5 grootste luchtvaartmaatschappijen Azië", answers: ["emirates", "singapore airlines", "qatar airways", "ana", "cathay pacific"] },
  { person: "Top 5 duurste wijnen ter wereld", answers: ["romanee-conti", "chateau lafite rothschild", "screaming eagle", "pétrus", "drc la tache"] },
  { person: "Top 5 populairste kookboeken", answers: ["jamie oliver", "gordon ramsay", "nigella lawson", "martha stewart", "yotam ottolenghi"] },
  { person: "Top 5 populairste sneakers wereldwijd", answers: ["nike air jordan", "adidas yeezy", "nike air max", "converse all star", "puma suede"] },
  { person: "Top 5 populairste koffieketens", answers: ["starbucks", "dunkin", "tim hortons", "peet's coffee", "coffee bean"] },
  { person: "Top 5 bekendste striphelden", answers: ["superman", "batman", "spiderman", "wonder woman", "iron man"] },
  { person: "Top 5 populairste muziekinstrumenten in scholen", answers: ["piano", "gitaar", "viool", "drums", "blokfluit"] },
  { person: "Top 5 populairste vakantielanden", answers: ["frankrijk", "spanje", "italië", "turkije", "greek"] },
  { person: "Top 5 grootste pretparken Europa", answers: ["disneyland paris", "europa-park", "port aventura", "efteling", "walibi belgium"] },
  { person: "Top 5 populairste ijssmaken", answers: ["vanille", "chocolade", "aardbei", "stracciatella", "cookies & cream"] },
  { person: "Top 5 populairste boardgames ter wereld", answers: ["monopoly", "chess", "risk", "cluedo", "catan"] },
  { person: "Top 5 grootste steden Azië", answers: ["tokyo", "delhi", "shanghai", "beijing", "mumbai"] },
  { person: "Top 5 grootste steden Europa", answers: ["moscow", "london", "berlin", "madrid", "rome"] },
  { person: "Top 5 bekendste filmregisseurs", answers: ["spielberg", "nolan", "tarantino", "kubrick", "scorsese"] },
  { person: "Top 5 duurste hotels ter wereld", answers: ["burj al arab", "emirates palace", "the plaza", "marina bay sands", "the ritz paris"] },
  { person: "Top 5 populairste diersoorten in dierentuinen", answers: ["olifant", "leeuw", "tijger", "panda", "giraffe"] },
  { person: "Top 5 grootste woestijnen", answers: ["sahara", "arabië", "gobi", "kalahari", "patagonië"] },
  { person: "Top 5 populairste fruitsmaken in smoothies", answers: ["aardbei", "banaan", "mango", "bosbes", "appel"] },
  { person: "Top 5 populairste festivals België", answers: ["tomorrowland", "rock werchter", "gentse feesten", "pukkelpop", "dranouter"] },
  { person: "Top 5 bekendste detectives uit boeken", answers: ["sherlock holmes", "hercule poirot", "miss marple", "sam spade", "philip marlowe"] },
  { person: "Top 5 grootste techbedrijven Azië", answers: ["tencent", "alibaba", "samsung", "baidu", "sony"] },
  { person: "Top 5 grootste techbedrijven VS", answers: ["apple", "microsoft", "amazon", "google", "meta"] },
  { person: "Top 5 grootste techbedrijven Europa", answers: ["spotify", "spotify", "sap", "nokia", "siemens"] },
  { person: "Top 5 populairste mobiele games", answers: ["clash of clans", "pokemon go", "subway surfers", "candy crush", "among us"] },
  { person: "Top 5 populairste streamingdiensten", answers: ["netflix", "disney+", "prime video", "hbo max", "hulu"] },
  { person: "Top 5 populairste fastfoodrestaurants wereldwijd", answers: ["mcdonalds", "burger king", "kfc", "subway", "pizza hut"] },
  { person: "Top 5 grootste biermerken wereldwijd", answers: ["budweiser", "heineken", "carlsberg", "stella artois", "corona"] },
  { person: "Top 5 populairste chocolademerken", answers: ["lindt", "godiva", "milka", "hershey's", "galler"] },
  { person: "Top 5 populairste parfummerken", answers: ["chanel", "dior", "gucci", "versace", "ysl"] },
  { person: "Top 5 populairste automerken ter wereld", answers: ["toyota", "volkswagen", "ford", "honda", "chevrolet"] },
  { person: "Top 5 populairste sportmerken", answers: ["nike", "adidas", "puma", "reebok", "under armour"] },
  { person: "Top 5 bekendste boekenseries", answers: ["harry potter", "lord of the rings", "game of thrones", "the hunger games", "twilight"] },
  { person: "Top 5 bekendste dansstijlen", answers: ["ballet", "hiphop", "salsa", "tango", "jazz"] },
  { person: "Top 5 populairste yogastijlen", answers: ["hatha", "vinyasa", "ashtanga", "yin", "kundalini"] },
  { person: "Top 5 meest bekeken films op Netflix", answers: ["bird box", "red notice", "the gray man", "don't look up", "stranger things"] },
  { person: "Top 5 bekendste cartoonfiguren", answers: ["mickey mouse", "donald duck", "bugs bunny", "spongebob", "tom & jerry"] },
  { person: "Top 5 bekendste superheldenfilms", answers: ["avengers", "batman", "spiderman", "iron man", "wonder woman"] },
  { person: "Top 5 populairste muziekgenres", answers: ["pop", "rock", "rap", "jazz", "classical"] },
  { person: "Top 5 bekendste jazzmusici", answers: ["louis armstrong", "miles davis", "john coltrane", "dizzy gillespie", "ella fitzgerald"] },
  { person: "Top 5 meest gebruikte sociale media apps", answers: ["facebook", "instagram", "tiktok", "twitter", "snapchat"] },
  { person: "Top 5 populairste fruitsappen", answers: ["appel", "sinaasappel", "mango", "ananas", "cranberry"] },
  { person: "Top 5 bekendste wetenschappers", answers: ["einstein", "newton", "curie", "darwin", "galilei"] },
  { person: "Top 5 populairste streamingmuziekdiensten", answers: ["spotify", "apple music", "youtube music", "tidal", "amazon music"] },
  { person: "Top 5 populairste videogames ooit", answers: ["minecraft", "tetris", "grand theft auto v", "wii sports", "fortnite"] },
  { person: "Top 5 populairste supermarkten wereldwijd", answers: ["walmart", "costco", "aldi", "tesco", "carrefour"] },
  { person: "Top 5 bekendste animatiefilms", answers: ["lion king", "frozen", "toy story", "shrek", "finding nemo"] },
  { person: "Top 5 grootste rivieren Noord-Amerika", answers: ["mississippi", "missouri", "yukon", "colorado", "columbia"] },
  { person: "Top 5 grootste rivieren Zuid-Amerika", answers: ["amazone", "paraná", "madeira", "negro", "são francisco"] },
  { person: "Top 5 grootste eilanden Afrika", answers: ["madagaskar", "mozambique", "borneo", "sri lanka", "sumatra"] },
  { person: "Top 5 populairste yogahoudingen", answers: ["downward dog", "cobra", "warrior", "tree pose", "child's pose"] },
  { person: "Top 5 bekendste sportevenementen ter wereld", answers: ["fifa wereldbeker", "olympische spelen", "super bowl", "wimbledon", "tour de france"] },
  { person: "Top 5 grootste steden Australië", answers: ["sydney", "melbourne", "brisbane", "perth", "adelaide"] },
  { person: "Top 5 bekendste filmmuziekcomponisten", answers: ["john williams", "hans zimmer", "ennio morricone", "danny elfman", "alan silvestri"] },
  { person: "Top 5 duurste automerken ter wereld", answers: ["rolls-royce", "bugatti", "bentley", "lamborghini", "ferrari"] },
  { person: "Top 5 populairste automerken wereldwijd", answers: ["toyota", "volkswagen", "honda", "hyundai", "ford"] },
  { person: "Top 5 Duitse automerken", answers: ["mercedes-benz", "bmw", "audi", "porsche", "volkswagen"] },
  { person: "Top 5 Italiaanse automerken", answers: ["ferrari", "lamborghini", "maserati", "fiat", "alfaromeo"] },
  { person: "Top 5 Japanse automerken", answers: ["toyota", "honda", "nissan", "mazda", "subaru"] },
  { person: "Top 5 elektrische automerken", answers: ["tesla", "byd", "nio", "rivian", "lucid"] },
  { person: "Top 5 Franse automerken", answers: ["renault", "peugeot", "citroen", "bugatti", "ds automobiles"] },
  { person: "Top 5 Amerikaanse automerken", answers: ["ford", "chevrolet", "tesla", "cadillac", "jeep"] },
  { person: "Top 5 Britse automerken", answers: ["aston martin", "rolls-royce", "bentley", "land rover", "mini"] },
  { person: "Top 5 Zuid-Koreaanse automerken", answers: ["hyundai", "kia", "genesis", "daewoo", "ssangyong"] },
  { person: "Top 5 Chinese automerken", answers: ["byd", "geely", "changan", "great wall", "nio"] },
  { person: "Top 5 sportautomerken", answers: ["ferrari", "lamborghini", "mclaren", "porsche", "aston martin"] },
  { person: "Top 5 luxueuze SUV-merken", answers: ["range rover", "bentley", "rolls-royce", "porsche", "mercedes-benz"] },
  { person: "Top 5 automerken met de hoogste verkoop in 2024", answers: ["toyota", "volkswagen", "hyundai", "honda", "ford"] },
  { person: "Top 5 automerken met de langste geschiedenis", answers: ["peugeot", "mercedes-benz", "ford", "fiat", "renault"] }
];



